### ISSUE TITLE
test suite failure

### ISSUE THREAD

**Issue by jkachmar** [23prime/oeis2#1]
`oes2-1.0.6` failed in a recent Stackage test run with the following error message:

```
      test/Spec.hs:29:5:
      1) Test for lookupSeq Compare lookup by ID with by SubSeq

[ generated example elided ]

      To rerun use: --match "/Test for lookupSeq/Compare lookup by ID with by SubSeq/"

    Randomized with seed 1521710722

    Finished in 1.4243 seconds
    4 examples, 1 failure
```

**Comment by 23prime** [comment]
Thanks for telling.

The tests has external API calling, so maybe, an accidental network error has occurred.

Now, all tests is passed with any runtime versions:
https://github.com/23prime/oeis2/actions/runs/1806922855
