### ISSUE TITLE
Lookups fail to return any results

### ISSUE THREAD

**Issue by byorgey** [23prime/oeis2#8]
I'm not sure if I'm doing something wrong, but using `oeis2-1.0.8` on GHC 9.8.2 it seems like I get no results.  As you can see from the below, it seems suitable results are coming back from the server as JSON, but maybe they are not getting parsed properly?

```
λ> :set -XOverloadedStrings 
λ> :m +Math.OEIS
λ> searchSeq' (ID "A000027") 0
[]
λ> :m +Math.OEIS.Internal 
λ> import qualified Data.Text as T
λ> T.take 100 <$> getJSON (ID "A000027") 0
"[\n\t{\n\t\t\"number\": 27,\n\t\t\"id\": \"M0472 N0173\",\n\t\t\"data\": \"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,"
```

Happy to provide whatever additional info and assistance I can.

**Comment by 23prime** [comment]
Thanks for telling.

OEIS API removed a top-level property `results`.
So it failed to parse.

I just published it on [Hackage](https://hackage.haskell.org/package/oeis2) as 1.0.9.
It will soon be available on Stackage as well.

**Comment by byorgey** [comment]
Thanks!
